// Code generated by protoc-gen-go. DO NOT EDIT.
// source: multiplayer.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlayerInfo struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Texture              string   `protobuf:"bytes,2,opt,name=texture,proto3" json:"texture,omitempty"`
	X                    int32    `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aa26acf9fa36b3a, []int{0}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func (m *PlayerInfo) GetTexture() string {
	if m != nil {
		return m.Texture
	}
	return ""
}

func (m *PlayerInfo) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *PlayerInfo) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type PlayerLocation struct {
	Texture              string   `protobuf:"bytes,1,opt,name=texture,proto3" json:"texture,omitempty"`
	X                    int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerLocation) Reset()         { *m = PlayerLocation{} }
func (m *PlayerLocation) String() string { return proto.CompactTextString(m) }
func (*PlayerLocation) ProtoMessage()    {}
func (*PlayerLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aa26acf9fa36b3a, []int{1}
}

func (m *PlayerLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerLocation.Unmarshal(m, b)
}
func (m *PlayerLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerLocation.Marshal(b, m, deterministic)
}
func (m *PlayerLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerLocation.Merge(m, src)
}
func (m *PlayerLocation) XXX_Size() int {
	return xxx_messageInfo_PlayerLocation.Size(m)
}
func (m *PlayerLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerLocation.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerLocation proto.InternalMessageInfo

func (m *PlayerLocation) GetTexture() string {
	if m != nil {
		return m.Texture
	}
	return ""
}

func (m *PlayerLocation) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *PlayerLocation) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*PlayerInfo)(nil), "PlayerInfo")
	proto.RegisterType((*PlayerLocation)(nil), "PlayerLocation")
}

func init() {
	proto.RegisterFile("multiplayer.proto", fileDescriptor_4aa26acf9fa36b3a)
}

var fileDescriptor_4aa26acf9fa36b3a = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x2d, 0xcd, 0x29,
	0xc9, 0x2c, 0xc8, 0x49, 0xac, 0x4c, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x0a, 0xe1,
	0xe2, 0x0a, 0x00, 0xf3, 0x3d, 0xf3, 0xd2, 0xf2, 0x85, 0x04, 0xb8, 0x98, 0xb3, 0xca, 0x4b, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x21, 0x09, 0x2e, 0xf6, 0x92, 0xd4, 0x8a, 0x92,
	0xd2, 0xa2, 0x54, 0x09, 0x26, 0xb0, 0x28, 0x8c, 0x2b, 0xc4, 0xc3, 0xc5, 0x58, 0x21, 0xc1, 0xac,
	0xc0, 0xa8, 0xc1, 0x1a, 0xc4, 0x58, 0x01, 0xe2, 0x55, 0x4a, 0xb0, 0x40, 0x78, 0x95, 0x4a, 0x6e,
	0x5c, 0x7c, 0x10, 0x53, 0x7d, 0xf2, 0x93, 0x13, 0x4b, 0x32, 0xf3, 0xf3, 0x90, 0xcd, 0x61, 0xc4,
	0x62, 0x0e, 0x13, 0x8a, 0x39, 0x50, 0x53, 0x2b, 0x8d, 0xec, 0xb8, 0x84, 0x7c, 0x11, 0x4e, 0x0e,
	0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0xd2, 0xe0, 0x62, 0x01, 0x99, 0x2e, 0xc4, 0xad, 0x87,
	0x70, 0xba, 0x14, 0xbf, 0x1e, 0xaa, 0x8d, 0x1a, 0x8c, 0x06, 0x8c, 0x4e, 0xea, 0x51, 0xaa, 0xe9,
	0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0xc9, 0x49, 0xf9, 0x25, 0x25, 0xa9,
	0x46, 0x86, 0xfa, 0x48, 0xc1, 0xa0, 0x9b, 0x9e, 0xaf, 0x5f, 0x90, 0x94, 0xc4, 0x06, 0x0e, 0x0d,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x72, 0xfa, 0x52, 0xa0, 0x22, 0x01, 0x00, 0x00,
}
