// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: hive.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HiveServiceClient is the client API for HiveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HiveServiceClient interface {
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*Player, error)
	Disconnect(ctx context.Context, in *Player, opts ...grpc.CallOption) (*Void, error)
}

type hiveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHiveServiceClient(cc grpc.ClientConnInterface) HiveServiceClient {
	return &hiveServiceClient{cc}
}

func (c *hiveServiceClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*Player, error) {
	out := new(Player)
	err := c.cc.Invoke(ctx, "/HiveService/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hiveServiceClient) Disconnect(ctx context.Context, in *Player, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/HiveService/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HiveServiceServer is the server API for HiveService service.
// All implementations must embed UnimplementedHiveServiceServer
// for forward compatibility
type HiveServiceServer interface {
	Join(context.Context, *JoinRequest) (*Player, error)
	Disconnect(context.Context, *Player) (*Void, error)
	mustEmbedUnimplementedHiveServiceServer()
}

// UnimplementedHiveServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHiveServiceServer struct {
}

func (UnimplementedHiveServiceServer) Join(context.Context, *JoinRequest) (*Player, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedHiveServiceServer) Disconnect(context.Context, *Player) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedHiveServiceServer) mustEmbedUnimplementedHiveServiceServer() {}

// UnsafeHiveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HiveServiceServer will
// result in compilation errors.
type UnsafeHiveServiceServer interface {
	mustEmbedUnimplementedHiveServiceServer()
}

func RegisterHiveServiceServer(s grpc.ServiceRegistrar, srv HiveServiceServer) {
	s.RegisterService(&HiveService_ServiceDesc, srv)
}

func _HiveService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HiveServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HiveService/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HiveServiceServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HiveService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Player)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HiveServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HiveService/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HiveServiceServer).Disconnect(ctx, req.(*Player))
	}
	return interceptor(ctx, in, info, handler)
}

// HiveService_ServiceDesc is the grpc.ServiceDesc for HiveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HiveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HiveService",
	HandlerType: (*HiveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _HiveService_Join_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _HiveService_Disconnect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hive.proto",
}
