// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hive.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Jwt struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Jwt) Reset()         { *m = Jwt{} }
func (m *Jwt) String() string { return proto.CompactTextString(m) }
func (*Jwt) ProtoMessage()    {}
func (*Jwt) Descriptor() ([]byte, []int) {
	return fileDescriptor_d635d1ead41ba02c, []int{0}
}

func (m *Jwt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Jwt.Unmarshal(m, b)
}
func (m *Jwt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Jwt.Marshal(b, m, deterministic)
}
func (m *Jwt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Jwt.Merge(m, src)
}
func (m *Jwt) XXX_Size() int {
	return xxx_messageInfo_Jwt.Size(m)
}
func (m *Jwt) XXX_DiscardUnknown() {
	xxx_messageInfo_Jwt.DiscardUnknown(m)
}

var xxx_messageInfo_Jwt proto.InternalMessageInfo

func (m *Jwt) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type Player struct {
	XId                  string   `protobuf:"bytes,1,opt,name=_id,json=Id,proto3" json:"_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_d635d1ead41ba02c, []int{1}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_d635d1ead41ba02c, []int{2}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type Bool struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bool) Reset()         { *m = Bool{} }
func (m *Bool) String() string { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()    {}
func (*Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_d635d1ead41ba02c, []int{3}
}

func (m *Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool.Unmarshal(m, b)
}
func (m *Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool.Marshal(b, m, deterministic)
}
func (m *Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool.Merge(m, src)
}
func (m *Bool) XXX_Size() int {
	return xxx_messageInfo_Bool.Size(m)
}
func (m *Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Bool proto.InternalMessageInfo

func (m *Bool) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*Jwt)(nil), "Jwt")
	proto.RegisterType((*Player)(nil), "Player")
	proto.RegisterType((*Void)(nil), "Void")
	proto.RegisterType((*Bool)(nil), "Bool")
}

func init() {
	proto.RegisterFile("hive.proto", fileDescriptor_d635d1ead41ba02c)
}

var fileDescriptor_d635d1ead41ba02c = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0x87, 0xd3, 0x37, 0xc9, 0xbe, 0x38, 0x1e, 0x94, 0x05, 0xff, 0x34, 0x87, 0x50, 0xf6, 0xe4,
	0xc5, 0x0d, 0xd6, 0x6f, 0x50, 0x3c, 0x68, 0x2e, 0x4a, 0x04, 0x0f, 0x5e, 0xa4, 0xd9, 0x0c, 0xed,
	0x48, 0xba, 0x53, 0x92, 0x69, 0x82, 0xf8, 0xe5, 0x25, 0x69, 0x04, 0x6f, 0x33, 0xcc, 0xef, 0x99,
	0x87, 0x19, 0x80, 0x2d, 0x75, 0x68, 0xf7, 0x0d, 0x0b, 0x9b, 0x2b, 0x08, 0xf3, 0x5e, 0xf4, 0x39,
	0x84, 0x9f, 0xbd, 0x5c, 0xcf, 0x16, 0xb3, 0x9b, 0x93, 0x62, 0x28, 0xcd, 0x1c, 0xd4, 0x4b, 0xbd,
	0xfe, 0xc2, 0x46, 0x9f, 0x41, 0xf8, 0x41, 0xd5, 0x34, 0xfb, 0xf7, 0x54, 0x19, 0x05, 0xd1, 0x1b,
	0x53, 0x65, 0x52, 0x88, 0x56, 0xcc, 0xb5, 0xbe, 0x04, 0xd5, 0xca, 0x5a, 0x0e, 0xed, 0x98, 0x89,
	0x8b, 0xa9, 0x5b, 0x7e, 0xc3, 0xe9, 0x23, 0x75, 0xf8, 0x8a, 0x4d, 0x47, 0x0e, 0xf5, 0x05, 0x44,
	0x39, 0x93, 0xd7, 0x91, 0xcd, 0x7b, 0x49, 0x62, 0x3b, 0xb0, 0x26, 0xd0, 0x29, 0xc0, 0x03, 0xb5,
	0x8e, 0xbd, 0x47, 0x27, 0xfa, 0xbf, 0x3d, 0x5a, 0x93, 0xd8, 0x8e, 0x8e, 0x40, 0xcf, 0x41, 0x15,
	0x58, 0x21, 0xee, 0x26, 0xf0, 0x37, 0x61, 0x02, 0x9d, 0x80, 0x7a, 0xf6, 0x35, 0x79, 0xfc, 0x8b,
	0x1d, 0xd7, 0xae, 0x16, 0xef, 0xe9, 0x86, 0x64, 0x7b, 0x28, 0xad, 0xe3, 0x5d, 0xe6, 0x4a, 0x16,
	0xc1, 0xe5, 0x5d, 0x36, 0x9c, 0x7e, 0xbb, 0xe1, 0x6c, 0x5f, 0x96, 0x6a, 0xfc, 0xc0, 0xfd, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x74, 0xb4, 0x33, 0x79, 0x0f, 0x01, 0x00, 0x00,
}
